import React,{useEffect,useState} from 'react';
import {Link} from 'react-router-dom';
import {api} from '../api';
function Badge({v}){const cls=(v||'').includes('PAID')||v==='READY'||v==='ACTIVE'?'green':(v||'').includes('PARTIAL')?'amber':v==='DELAYED'||v==='HOLD'?'red':'gray';return <span className={'badge '+cls}>{v}</span>}
export default function MasterControl(){const [summary,setSummary]=useState({}),[orders,setOrders]=useState([]),[priority,setPriority]=useState([]),[cap,setCap]=useState([]),[forecast,setForecast]=useState([]);
 useEffect(()=>{Promise.all([api('/master/summary'),api('/orders'),api('/master/morning-priority'),api('/master/wip-capacity'),api('/master/forecast')]).then(([a,b,c,d,e])=>{setSummary(a);setOrders(b);setPriority(c);setCap(d);setForecast(e)})},[])
 return <div className="page"><div className="page-title"><div><h1>Master Control</h1><p>Control Tower • Morning Meeting • lintas divisi</p></div></div>
 <div className="cards"><Card n={summary.critical||0} t="Critical" tone="red"/><Card n={summary.attention||0} t="Attention" tone="amber"/><Card n={summary.on_track||0} t="On Track" tone="green"/><Card n={summary.waiting||0} t="Waiting" tone="gray"/></div>
 <section className="panel"><div className="panel-head"><h2>Morning Priority</h2><span>Auto dari exception & gate</span></div><div className="table-scroll"><table><thead><tr><th>#</th><th>Order</th><th>Masalah</th><th>Owner</th><th>Due</th><th>Next Action</th></tr></thead><tbody>{priority.map((r,i)=><tr key={r.id}><td><i className={'dot '+r.severity.toLowerCase()}></i>{i+1}</td><td>{r.order_id}</td><td>{r.title}</td><td>{r.owner}</td><td>{r.due_date||'-'}</td><td>{r.next_action||'-'}</td></tr>)}</tbody></table></div></section>
 <div className="grid2"><section className="panel"><div className="panel-head"><h2>Master Produksi</h2><span>{orders.length} order</span></div><div className="table-scroll"><table><thead><tr><th>Order ID</th><th>Buyer</th><th>Article</th><th>Qty</th><th>Deadline</th><th>Finance</th><th>Material</th><th>Status</th></tr></thead><tbody>{orders.map(o=><tr key={o.id}><td><Link to={'/orders/'+o.order_id}>{o.order_id}</Link></td><td>{o.buyer}</td><td>{o.articles?.map(a=>a.article_code).join(', ')}</td><td>{o.articles?.reduce((s,a)=>s+a.qty,0)}</td><td>{o.buyer_deadline||'-'}</td><td><Badge v={o.finance_status}/></td><td><Badge v={o.material_status}/></td><td><Badge v={o.overall_status}/></td></tr>)}</tbody></table></div></section>
 <section className="panel"><div className="panel-head"><h2>WIP & Capacity</h2><span>Hari ini</span></div>{cap.map(c=><div className="caprow" key={c.process}><div><b>{c.process}</b><small>{c.planned_load} / {c.capacity} pcs • WIP {c.current_wip}</small></div><div className="bar"><span style={{width:Math.min(c.utilization,100)+'%'}}></span></div><b className={c.utilization>100?'danger':''}>{c.utilization}%</b></div>)}</section></div>
 <section className="panel"><div className="panel-head"><h2>Forecast Shipment</h2><span>Deadline vs proyeksi</span></div><div className="table-scroll"><table><thead><tr><th>Order</th><th>Buyer</th><th>Deadline</th><th>Projected</th><th>Buffer</th><th>Risk</th></tr></thead><tbody>{forecast.map(f=><tr key={f.order_id}><td>{f.order_id}</td><td>{f.buyer}</td><td>{f.deadline||'-'}</td><td>{f.projected_shipment||'-'}</td><td>{f.buffer_days??'-'}</td><td><Badge v={f.status}/></td></tr>)}</tbody></table></div></section>
 </div>}
function Card({n,t,tone}){return <div className={'stat '+tone}><strong>{n}</strong><span>{t}</span></div>}
