import React,{useEffect,useState} from 'react';
import {api} from '../api';
import {useRole} from '../components/Access';
import FormModal from '../components/FormModal';
const empty={order_fk:'',plan_date:'',status:'PLANNING',notes:''};
export default function ProductionPlanPage(){
 const canWrite=useRole()==='COO_MANAGER';const [plans,setPlans]=useState([]),[orders,setOrders]=useState([]),[err,setErr]=useState(''),[form,setForm]=useState(null),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true);
 async function load(){try{const [p,o]=await Promise.all([api('/coo/production-plans'),api('/orders')]);setPlans(p);setOrders(o);setErr('')}catch(e){setErr(e.message)}finally{setLoading(false)}}useEffect(()=>{load()},[]);
 async function save(e){e.preventDefault();setBusy(true);setErr('');try{await api('/coo/production-plans'+(form.id?'/'+form.id:''),{method:form.id?'PATCH':'POST',body:JSON.stringify({order_fk:Number(form.order_fk),plan_date:form.plan_date,status:form.status,notes:form.notes})});setForm(null);await load()}catch(e){setErr(e.message)}finally{setBusy(false)}}
 async function remove(id){if(!confirm('Hapus rencana produksi ini?'))return;try{await api('/coo/production-plans/'+id,{method:'DELETE'});await load()}catch(e){setErr(e.message)}}
 return <div className="page"><div className="page-title"><div><h1>Production Plan</h1><p>Rencana produksi per order setelah SPK dirilis.</p></div>{canWrite&&<button className="btn primary" onClick={()=>{setErr('');setForm({...empty})}}>Tambah Rencana</button>}</div>{err&&!form&&<div className="notice danger" role="alert">{err}</div>}{loading?<p>Memuat...</p>:<div className="table-scroll"><table><thead><tr><th>Order</th><th>Tanggal Rencana</th><th>Status</th><th>Catatan</th><th>Aksi</th></tr></thead><tbody>{plans.map(p=><tr key={p.id}><td>{orders.find(o=>o.id===p.order_fk)?.order_id||p.order_fk}</td><td>{p.plan_date||'—'}</td><td>{p.status}</td><td>{p.notes}</td><td>{canWrite&&<><button className="btn" onClick={()=>{setErr('');setForm({...empty,...p})}}>Edit</button><button className="btn" onClick={()=>remove(p.id)}>Hapus</button></>}</td></tr>)}{!plans.length&&<tr><td colSpan={5}>Belum ada rencana produksi.</td></tr>}</tbody></table></div>}{form&&<FormModal title="Rencana Produksi" onSubmit={save} onClose={()=>setForm(null)} busy={busy} error={err}><label>Order<select required disabled={Boolean(form.id)} value={form.order_fk} onChange={e=>setForm({...form,order_fk:e.target.value})}><option value="">Pilih order</option>{orders.filter(o=>o.order_type!=='SAMPLE_ONLY').map(o=><option key={o.id} value={o.id}>{o.order_id}</option>)}</select></label><label>Tanggal Rencana<input type="date" required value={form.plan_date||''} onChange={e=>setForm({...form,plan_date:e.target.value})}/></label><label>Status<select value={form.status} onChange={e=>setForm({...form,status:e.target.value})}>{['PLANNING','APPROVED','RELEASED','IN_PROGRESS','DONE','CANCELLED'].map(s=><option key={s}>{s}</option>)}</select></label><label>Catatan<textarea value={form.notes||''} onChange={e=>setForm({...form,notes:e.target.value})}/></label></FormModal>}</div>;
}
