import React,{useEffect,useState} from 'react';
import {api} from '../api';
import {useRole} from '../components/Access';
import FormModal from '../components/FormModal';
import {matchesSearch,statusTone} from '../business';

const empty={order_fk:'',shipment_no:'',status:'PREPARING',packing_status:'PENDING',tracking_no:'',shipped_date:'',delivery_date:'',notes:''};
export default function ShipmentListPage(){
 const role=useRole(),canShip=['COO_MANAGER','SHIPMENT_ADMIN'].includes(role);
 const [list,setList]=useState([]),[orders,setOrders]=useState([]),[form,setForm]=useState(null),[decision,setDecision]=useState(null),[busy,setBusy]=useState(false),[err,setErr]=useState(''),[q,setQ]=useState(''),[loading,setLoading]=useState(true);
 async function load(){try{const [s,o]=await Promise.all([api('/coo/shipments'),api('/orders')]);setList(s);setOrders(o);setErr('')}catch(e){setErr(e.message)}finally{setLoading(false)}}
 useEffect(()=>{load()},[]);
 async function save(e){e.preventDefault();setBusy(true);setErr('');try{const payload={status:form.status,packing_status:form.packing_status,tracking_no:form.tracking_no,shipped_date:form.shipped_date,delivery_date:form.delivery_date,notes:form.notes};if(!form.id)Object.assign(payload,{order_fk:Number(form.order_fk),shipment_no:form.shipment_no});await api('/coo/shipments'+(form.id?'/'+form.id:''),{method:form.id?'PATCH':'POST',body:JSON.stringify(payload)});setForm(null);await load()}catch(e){setErr(e.message)}finally{setBusy(false)}}
 async function approve(e){e.preventDefault();setBusy(true);setErr('');try{await api(decision.ceo?`/ceo/shipments/${decision.id}/approve-shipment`:`/cfo/shipments/${decision.id}/gate`,{method:'POST',body:JSON.stringify({action:decision.action,reason:decision.reason})});setDecision(null);await load()}catch(e){setErr(e.message)}finally{setBusy(false)}}
 const label=id=>orders.find(o=>o.id===id)?.order_id||id;
 return <div className="page"><div className="page-title"><div><h1>Shipment & Finance Gate</h1><p>CFO menilai release; CEO menyetujui pengecualian outstanding; COO mengirim.</p></div>{canShip&&<button className="btn primary" onClick={()=>{setErr('');setForm({...empty})}}>Tambah Shipment</button>}</div>
 {err&&!form&&!decision&&<div role="alert" className="notice danger">{err}</div>}<input aria-label="Cari shipment" placeholder="Cari shipment / catatan" value={q} onChange={e=>setQ(e.target.value)}/>
 {loading?<p>Memuat...</p>:<div className="table-scroll"><table><thead><tr><th>Order</th><th>Shipment</th><th>Status / Packing</th><th>Finance / CEO</th><th>Resi / Tanggal</th><th>Aksi</th></tr></thead><tbody>{list.filter(s=>matchesSearch(s,q,['shipment_no','notes'])).map(s=><tr key={s.id}><td>{label(s.order_fk)}</td><td>{s.shipment_no}</td><td>{s.status}<br/>{s.packing_status||'PENDING'}</td><td><span className={'badge '+statusTone(s.finance_gate)}>{s.finance_gate}</span><br/><span className={'badge '+statusTone(s.ceo_approval)}>{s.ceo_approval||'NOT_REQUIRED'}</span></td><td>{s.tracking_no||'—'}<br/>{s.shipped_date||'—'}</td><td>{canShip&&<button className="btn" onClick={()=>{setErr('');setForm({...empty,...s})}}>Edit</button>}{role==='CFO_MANAGER'&&!['SHIPPED','DELIVERED'].includes(s.status)&&['APPROVE','REJECT'].map(action=><button key={action} className="btn" onClick={()=>{setErr('');setDecision({id:s.id,action,ceo:false,reason:''})}}>{action==='APPROVE'?'Setujui':'Hold / Tolak'}</button>)}{role==='CEO'&&s.ceo_approval==='PENDING'&&['APPROVE','REJECT'].map(action=><button key={action} className="btn" onClick={()=>{setErr('');setDecision({id:s.id,action,ceo:true,reason:''})}}>CEO: {action==='APPROVE'?'Setujui':'Tolak'}</button>)}</td></tr>)}{!list.length&&<tr><td colSpan={6}>Belum ada shipment.</td></tr>}</tbody></table></div>}
 {form&&<FormModal title={form.id?'Edit Shipment':'Shipment Baru'} error={err} busy={busy} onClose={()=>setForm(null)} onSubmit={save}>{!form.id&&<><label>Order<select required value={form.order_fk} onChange={e=>setForm({...form,order_fk:e.target.value})}><option value="">Pilih order</option>{orders.filter(o=>o.order_type!=='SAMPLE_ONLY').map(o=><option key={o.id} value={o.id}>{o.order_id}</option>)}</select></label><label>Nomor Shipment<input required value={form.shipment_no} onChange={e=>setForm({...form,shipment_no:e.target.value})}/></label></>}<div className="form-grid"><label>Status<select value={form.status} onChange={e=>setForm({...form,status:e.target.value})}>{['NOT_READY','PREPARING','SHIPPED'].map(s=><option key={s}>{s}</option>)}</select></label><label>Packing<select value={form.packing_status} onChange={e=>setForm({...form,packing_status:e.target.value})}><option>PENDING</option><option>PACKED</option></select></label></div><p className="notice info">Status pengiriman diperiksa di server. Delivery selesai hanya melalui konfirmasi customer.</p><label>Nomor Resi<input value={form.tracking_no||''} onChange={e=>setForm({...form,tracking_no:e.target.value})}/></label><div className="form-grid">{[['shipped_date','Tanggal Kirim'],['delivery_date','Tanggal Tiba']].map(([k,label])=><label key={k}>{label}<input type="date" value={form[k]||''} onChange={e=>setForm({...form,[k]:e.target.value})}/></label>)}</div><label>Catatan<textarea value={form.notes||''} onChange={e=>setForm({...form,notes:e.target.value})}/></label></FormModal>}
 {decision&&<FormModal title={`${decision.ceo?'CEO':'CFO'} — ${decision.action}`} error={err} busy={busy} onClose={()=>setDecision(null)} onSubmit={approve}><label>Alasan dan bukti penilaian<textarea required value={decision.reason} onChange={e=>setDecision({...decision,reason:e.target.value})}/></label></FormModal>}</div>;
}
