import React,{useEffect,useState} from 'react';
import {api} from '../api';
import {useRole} from '../components/Access';
import FormModal from '../components/FormModal';
import {matchesSearch,statusTone} from '../business';

const emptyLine={article_id:'',qty:''};
const empty={order_fk:'',shipment_no:'',status:'PREPARING',packing_status:'PENDING',tracking_no:'',shipped_date:'',notes:'',lines:[]};

export default function ShipmentListPage(){
 const role=useRole(),canShip=['COO_MANAGER','SHIPMENT_ADMIN'].includes(role);
 const [list,setList]=useState([]),[orders,setOrders]=useState([]),[form,setForm]=useState(null),[decision,setDecision]=useState(null),[handover,setHandover]=useState(null),[busy,setBusy]=useState(false),[err,setErr]=useState(''),[q,setQ]=useState(''),[loading,setLoading]=useState(true);
 async function load(){try{const [s,o]=await Promise.all([api('/coo/shipments'),api('/orders')]);setList(s);setOrders(o);setErr('')}catch(e){setErr(e.message)}finally{setLoading(false)}}
 useEffect(()=>{load()},[]);
 async function save(e){e.preventDefault();setBusy(true);setErr('');try{const payload={status:form.status,packing_status:form.packing_status,tracking_no:form.tracking_no,shipped_date:form.shipped_date,notes:form.notes};if(!form.id||form.lines?.length)payload.lines=(form.lines||[]).map(line=>({article_id:Number(line.article_id),qty:Number(line.qty)}));if(!form.id)Object.assign(payload,{order_fk:Number(form.order_fk),shipment_no:form.shipment_no});await api('/coo/shipments'+(form.id?'/'+form.id:''),{method:form.id?'PATCH':'POST',body:JSON.stringify(payload)});setForm(null);await load()}catch(e){setErr(e.message)}finally{setBusy(false)}}
 async function recordHandover(e){e.preventDefault();setBusy(true);setErr('');try{await api('/coo/shipments/'+handover.id,{method:'PATCH',body:JSON.stringify({status:'DELIVERED',delivery_date:handover.delivery_date})});setHandover(null);await load()}catch(e){setErr(e.message)}finally{setBusy(false)}}
 async function approve(e){e.preventDefault();setBusy(true);setErr('');try{await api(decision.ceo?`/ceo/shipments/${decision.id}/approve-shipment`:`/cfo/shipments/${decision.id}/gate`,{method:'POST',body:JSON.stringify({action:decision.action,reason:decision.reason})});setDecision(null);await load()}catch(e){setErr(e.message)}finally{setBusy(false)}}
 const label=id=>orders.find(o=>o.id===id)?.order_id||id;
 const shipmentArticles=orders.find(order=>order.id===Number(form?.order_fk))?.articles||[];
 const updateLine=(index,key,value)=>setForm(current=>({...current,lines:current.lines.map((line,i)=>i===index?{...line,[key]:value}:line)}));
 const openEdit=shipment=>setForm({...empty,...shipment,lines:(shipment.lines||[]).map(line=>({article_id:String(line.article_id),qty:String(line.qty)}))});
 return <div className="page"><div className="page-title"><div><h1>Shipment & Finance Gate</h1><p>CFO menilai release; CEO menyetujui pengecualian outstanding; COO mengirim, melacak, dan mencatat serah terima fisik. CMO melihat status shipment.</p></div>{canShip&&<button className="btn primary" onClick={()=>{setErr('');setForm({...empty})}}>Tambah Shipment</button>}</div>
 {err&&!form&&!decision&&!handover&&<div role="alert" className="notice danger">{err}</div>}<input aria-label="Cari shipment" placeholder="Cari shipment / catatan" value={q} onChange={e=>setQ(e.target.value)}/>
 {loading?<p>Memuat...</p>:<div className="table-scroll"><table><thead><tr><th>Order</th><th>Shipment</th><th>Article / Qty</th><th>Status / Packing</th><th>Finance / CEO</th><th>Resi / Tanggal</th><th>Aksi</th></tr></thead><tbody>{list.filter(s=>matchesSearch(s,q,['shipment_no','notes'])).map(s=><tr key={s.id}><td>{label(s.order_fk)}</td><td>{s.shipment_no}</td><td>{s.lines?.length?<>{s.lines.map(line=><div key={line.id||line.article_id}>{line.article_code||`Article #${line.article_id}`}: {line.qty}</div>)}<small>Total: {s.line_total_qty}</small></>:s.line_reconciliation_required?<span className="badge amber">Perlu rekonsiliasi</span>:'—'}</td><td>{s.status}<br/>{s.packing_status||'PENDING'}</td><td><span className={'badge '+statusTone(s.finance_gate)}>{s.finance_gate}</span><br/><span className={'badge '+statusTone(s.ceo_approval)}>{s.ceo_approval||'NOT_REQUIRED'}</span></td><td>{s.tracking_no||'—'}<br/>{s.shipped_date||'—'}<br/>{s.delivery_date&&`Serah terima: ${s.delivery_date}`}</td><td>{canShip&&s.status!=='DELIVERED'&&<button className="btn" onClick={()=>{setErr('');openEdit(s)}}>Edit / Tracking</button>}{role==='COO_MANAGER'&&(s.status==='SHIPPED'||(s.status==='DELIVERED'&&!s.delivery_date))&&<button className="btn" onClick={()=>{setErr('');setHandover({id:s.id,delivery_date:''})}}>{s.status==='DELIVERED'?'Verifikasi Serah Terima':'Catat Serah Terima'}</button>}{role==='CFO_MANAGER'&&!['SHIPPED','DELIVERED'].includes(s.status)&&['APPROVE','REJECT'].map(action=><button key={action} className="btn" onClick={()=>{setErr('');setDecision({id:s.id,action,ceo:false,reason:''})}}>{action==='APPROVE'?'Setujui':'Hold / Tolak'}</button>)}{role==='CEO'&&s.ceo_approval==='PENDING'&&['APPROVE','REJECT'].map(action=><button key={action} className="btn" onClick={()=>{setErr('');setDecision({id:s.id,action,ceo:true,reason:''})}}>CEO: {action==='APPROVE'?'Setujui':'Tolak'}</button>)}</td></tr>)}{!list.length&&<tr><td colSpan={7}>Belum ada shipment.</td></tr>}</tbody></table></div>}
 {form&&<FormModal title={form.id?'Edit Shipment':'Shipment Baru'} error={err} busy={busy} onClose={()=>setForm(null)} onSubmit={save}>{!form.id&&<><label>Order<select required value={form.order_fk} onChange={e=>setForm({...form,order_fk:e.target.value,lines:[]})}><option value="">Pilih order</option>{orders.filter(o=>o.order_type!=='SAMPLE_ONLY').map(o=><option key={o.id} value={o.id}>{o.order_id}</option>)}</select></label><label>Nomor Shipment<input required value={form.shipment_no} onChange={e=>setForm({...form,shipment_no:e.target.value})}/></label></>}<div className="form-grid"><label>Status<select value={form.status} onChange={e=>setForm({...form,status:e.target.value})}>{['NOT_READY','PREPARING','SHIPPED'].map(s=><option key={s}>{s}</option>)}</select></label><label>Packing<select value={form.packing_status} onChange={e=>setForm({...form,packing_status:e.target.value})}><option>PENDING</option><option>PACKED</option></select></label></div><section><div className="panel-head"><h3>Line packing per article</h3>{form.status!=='SHIPPED'&&<button type="button" className="btn sm" onClick={()=>setForm({...form,lines:[...(form.lines||[]),{...emptyLine}]})}>Tambah line</button>}</div><p className="notice info">Total setiap article tidak boleh melebihi quantity order, termasuk shipment lain. Shipment PACKED atau SHIPPED wajib memiliki line valid.</p>{(form.lines||[]).map((line,index)=><div className="form-grid" key={index}><label>Article<select required value={line.article_id} onChange={e=>updateLine(index,'article_id',e.target.value)}><option value="">Pilih article</option>{shipmentArticles.map(article=><option key={article.id} value={article.id}>{article.article_code} · order {article.qty}</option>)}</select></label><label>Qty packing<input required type="number" min="1" value={line.qty} onChange={e=>updateLine(index,'qty',e.target.value)}/></label><button type="button" className="btn danger" onClick={()=>setForm({...form,lines:form.lines.filter((_,i)=>i!==index)})}>Hapus line</button></div>)}{!(form.lines||[]).length&&<p>Belum ada line packing.</p>}</section><p className="notice info">Pengiriman dan tracking dicatat COO. Serah terima fisik dicatat terpisah setelah status SHIPPED.</p><label>Nomor Resi<input value={form.tracking_no||''} onChange={e=>setForm({...form,tracking_no:e.target.value})}/></label><label>Tanggal Kirim<input type="date" value={form.shipped_date||''} onChange={e=>setForm({...form,shipped_date:e.target.value})}/></label><label>Catatan<textarea value={form.notes||''} onChange={e=>setForm({...form,notes:e.target.value})}/></label></FormModal>}
 {handover&&<FormModal title="Catat / Verifikasi Serah Terima Fisik (COO)" error={err} busy={busy} onClose={()=>setHandover(null)} onSubmit={recordHandover}><label>Tanggal Serah Terima<input type="date" required value={handover.delivery_date} onChange={e=>setHandover({...handover,delivery_date:e.target.value})}/></label></FormModal>}
 {decision&&<FormModal title={`${decision.ceo?'CEO':'CFO'} — ${decision.action}`} error={err} busy={busy} onClose={()=>setDecision(null)} onSubmit={approve}><label>Alasan dan bukti penilaian<textarea required value={decision.reason} onChange={e=>setDecision({...decision,reason:e.target.value})}/></label></FormModal>}</div>;
}
